// Méthode / FAQ content — also emitted as FAQPage JSON-LD on /methode.
module.exports = {
  fr: [
    { q: "D'où viennent les données ?",
      a: "Trois jeux de données publics officiels, tous en licence Ouverte : le <b>Répertoire national des élus</b> (data.gouv.fr) pour l'identité des maires, l'<b>Observatoire des finances et de la gestion publique locales (OFGL)</b> pour les comptes des communes, et la <b>Haute Autorité pour la transparence de la vie publique (HATVP)</b> pour les déclarations d'intérêts. Aucune donnée n'est inventée ni estimée." },
    { q: "Le maire est-il responsable des chiffres financiers ?",
      a: "Pas nécessairement. Les élections municipales ont eu lieu en <b>mars 2026</b> : la plupart des maires viennent de prendre leurs fonctions. Les comptes présentés (dernier exercice publié, généralement 2024) décrivent l'état de la commune <b>héritée</b>, pas le bilan du mandat en cours. Nous l'indiquons clairement sur chaque fiche." },
    { q: "Que signifie la capacité de désendettement ?",
      a: "C'est le nombre d'années qu'il faudrait à la commune pour rembourser toute sa dette si elle y consacrait la totalité de son épargne brute (dette ÷ épargne brute). C'est l'indicateur de référence des Chambres régionales des comptes : en dessous de 8 ans la situation est saine, entre 8 et 12 ans elle est à surveiller, au-delà de 12 ans elle est tendue. Sur les très petites communes ce ratio est volatile." },
    { q: "Qu'est-ce que le taux d'épargne brute ?",
      a: "La part des recettes de fonctionnement qui reste une fois les dépenses de fonctionnement payées (épargne brute ÷ recettes de fonctionnement). C'est ce que la commune peut consacrer à l'investissement et au remboursement de la dette. Un taux supérieur à ~10 % est généralement considéré comme confortable." },
    { q: "Pourquoi certaines communes n'ont-elles pas de finances ?",
      a: "L'OFGL couvre la métropole et les DROM. Quelques collectivités d'outre-mer (Polynésie, Nouvelle-Calédonie, Wallis-et-Futuna…) n'y figurent pas encore : la fiche affiche alors l'identité du maire sans les comptes." },
    { q: "Pourquoi tous les maires ne déclarent-ils pas à la HATVP ?",
      a: "Seuls les maires des communes de plus de 20 000 habitants (et quelques autres cas) sont tenus de déposer une déclaration d'intérêts. Nous n'affichons que les <b>intérêts</b> déclarés — la déclaration de patrimoine des élus locaux n'est pas en open data." },
    { q: "Est-ce un site partisan ?",
      a: "Non. FicheDeMaire.fr n'exprime aucun avis et n'attribue aucune note morale. Chaque chiffre renvoie à sa source officielle. Projet indépendant, réalisé par zlef.fr." },
  ],
  en: [
    { q: "Where does the data come from?",
      a: "Three official French open datasets (Licence Ouverte): the <b>National Register of Elected Officials</b> for mayors' identity, the <b>Observatory of Local Public Finances (OFGL)</b> for town accounts, and the <b>High Authority for Transparency in Public Life (HATVP)</b> for declarations of interests. Nothing is invented or estimated." },
    { q: "Is the mayor responsible for the financial figures?",
      a: "Not necessarily. France held municipal elections in <b>March 2026</b>: most mayors have just taken office. The accounts shown (latest published year, usually 2024) describe the <b>inherited</b> state of the town, not the current term's record. We say so clearly on every page." },
    { q: "What is debt-repayment capacity?",
      a: "The number of years a town would need to repay all its debt if it devoted its entire gross savings to it (debt ÷ gross savings). It is the reference indicator of France's regional audit courts: under 8 years is healthy, 8–12 warrants watching, above 12 is stretched. On very small towns the ratio is volatile." },
    { q: "What is the gross savings rate?",
      a: "The share of operating revenue left once operating spend is paid (gross savings ÷ operating revenue) — what the town can put toward investment and debt repayment. Above ~10% is generally comfortable." },
    { q: "Why do some towns have no finances?",
      a: "OFGL covers mainland France and the overseas departments. A few overseas collectivities (French Polynesia, New Caledonia, Wallis and Futuna…) aren't included yet: the page then shows the mayor's identity without the accounts." },
    { q: "Why don't all mayors declare to HATVP?",
      a: "Only mayors of towns over 20,000 inhabitants (and a few other cases) must file a declaration of interests. We show only declared <b>interests</b> — local officials' asset declarations are not open data." },
    { q: "Is this a partisan site?",
      a: "No. FicheDeMaire.fr expresses no opinion and assigns no moral score. Every figure links back to its official source. An independent project by zlef.fr." },
  ],
};
